import { Pokemon } from "./pokemon";

export const POKEMONS: Pokemon[] = [
    {
      Id: 1,
      Name: "Bulbasaur",
      Type1: "Grass",
      Type2: "Poison",
      HP: 45,
      Attack: 49,
      Defense: 49,
      Speed: 45,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/bulbasaur.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/bulbasaur.png",
      Description: "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokemon."
    },
    {
      Id: 2,
      Name: "Ivysaur",
      Type1: "Grass",
      Type2: "Poison",
      HP: 60,
      Attack: 62,
      Defense: 63,
      Speed: 60,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ivysaur.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ivysaur.png",
      Description: "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa."
    },
    {
      Id: 3,
      Name: "Venusaur",
      Type1: "Grass",
      Type2: "Poison",
      HP: 80,
      Attack: 82,
      Defense: 83,
      Speed: 80,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/venusaur.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/venusaur.png",
      Description: "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning."
    },
    {
      Id: 4,
      Name: "Charmander",
      Type1: "Fire",
      Type2: "",
      HP: 39,
      Attack: 52,
      Defense: 43,
      Speed: 65,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/charmander.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/charmander.png",
      Description: "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail."
    },
    {
      Id: 5,
      Name: "Charmeleon",
      Type1: "Fire",
      Type2: "",
      HP: 58,
      Attack: 64,
      Defense: 58,
      Speed: 80,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/charmeleon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/charmeleon.png",
      Description: "When it swings its burning tail, it elevates the temperature to unbearably high levels."
    },
    {
      Id: 6,
      Name: "Charizard",
      Type1: "Fire",
      Type2: "Flying",
      HP: 78,
      Attack: 84,
      Defense: 78,
      Speed: 100,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/charizard.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/charizard.png",
      Description: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally."
    },
    {
      Id: 7,
      Name: "Squirtle",
      Type1: "Water",
      Type2: "",
      HP: 44,
      Attack: 48,
      Defense: 65,
      Speed: 43,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/squirtle.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/squirtle.png",
      Description: "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth."
    },
    {
      Id: 8,
      Name: "Wartortle",
      Type1: "Water",
      Type2: "",
      HP: 59,
      Attack: 63,
      Defense: 80,
      Speed: 58,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/wartortle.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/wartortle.png",
      Description: "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance."
    },
    {
      Id: 9,
      Name: "Blastoise",
      Type1: "Water",
      Type2: "",
      HP: 79,
      Attack: 83,
      Defense: 100,
      Speed: 78,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/blastoise.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/blastoise.png",
      Description: "A brutal Pokemon with pressurized water jets on its shell. They are used for high speed tackles."
    },
    {
      Id: 10,
      Name: "Caterpie",
      Type1: "Bug",
      Type2: "",
      HP: 45,
      Attack: 30,
      Defense: 35,
      Speed: 45,
      Special: 20,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/caterpie.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/caterpie.png",
      Description: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls."
    },
    {
      Id: 11,
      Name: "Metapod",
      Type1: "Bug",
      Type2: "",
      HP: 50,
      Attack: 20,
      Defense: 55,
      Speed: 30,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/metapod.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/metapod.png",
      Description: "This Pokemon is vulnerable to attack while its shell is soft, exposing its weak and tender body."
    },
    {
      Id: 12,
      Name: "Butterfree",
      Type1: "Bug",
      Type2: "Flying",
      HP: 60,
      Attack: 45,
      Defense: 50,
      Speed: 70,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/butterfree.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/butterfree.png",
      Description: "In battle, it flaps its wings at high speed to release highly toxic dust into the air."
    },
    {
      Id: 13,
      Name: "Weedle",
      Type1: "Bug",
      Type2: "Poison",
      HP: 40,
      Attack: 35,
      Defense: 30,
      Speed: 50,
      Special: 20,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/weedle.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/weedle.png",
      Description: "Often found in forests, eating leaves. It has a sharp venomous stinger on its head."
    },
    {
      Id: 14,
      Name: "Kakuna",
      Type1: "Bug",
      Type2: "Poison",
      HP: 45,
      Attack: 25,
      Defense: 50,
      Speed: 35,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kakuna.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kakuna.png",
      Description: "Almost incapable of moving, this Pokemon can only harden its shell to protect itself from predators."
    },
    {
      Id: 15,
      Name: "Beedrill",
      Type1: "Bug",
      Type2: "Poison",
      HP: 65,
      Attack: 80,
      Defense: 40,
      Speed: 75,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/beedrill.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/beedrill.png",
      Description: "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail."
    },
    {
      Id: 16,
      Name: "Pidgey",
      Type1: "Normal",
      Type2: "Flying",
      HP: 40,
      Attack: 45,
      Defense: 40,
      Speed: 56,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pidgey.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pidgey.png",
      Description: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand."
    },
    {
      Id: 17,
      Name: "Pidgeotto",
      Type1: "Normal",
      Type2: "Flying",
      HP: 63,
      Attack: 60,
      Defense: 55,
      Speed: 71,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pidgeotto.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pidgeotto.png",
      Description: "Very protective of its sprawling territorial area, this Pokemon will fiercely peck at any intruder."
    },
    {
      Id: 18,
      Name: "Pidgeot",
      Type1: "Normal",
      Type2: "Flying",
      HP: 83,
      Attack: 80,
      Defense: 75,
      Speed: 91,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pidgeot.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pidgeot.png",
      Description: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP."
    },
    {
      Id: 19,
      Name: "Rattata",
      Type1: "Normal",
      Type2: "",
      HP: 30,
      Attack: 56,
      Defense: 35,
      Speed: 72,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/rattata.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/rattata.png",
      Description: "Bites anything when it attacks. Small and very quick, it is a common sight in many places."
    },
    {
      Id: 20,
      Name: "Raticate",
      Type1: "Normal",
      Type2: "",
      HP: 55,
      Attack: 81,
      Defense: 60,
      Speed: 97,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/raticate.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/raticate.png",
      Description: "It uses its whiskers to maintain its balance. It apparently slows down if they are cut off."
    },
    {
      Id: 21,
      Name: "Spearow",
      Type1: "Normal",
      Type2: "Flying",
      HP: 40,
      Attack: 60,
      Defense: 30,
      Speed: 70,
      Special: 31,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/spearow.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/spearow.png",
      Description: "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne."
    },
    {
      Id: 22,
      Name: "Fearow",
      Type1: "Normal",
      Type2: "Flying",
      HP: 65,
      Attack: 90,
      Defense: 65,
      Speed: 100,
      Special: 61,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/fearow.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/fearow.png",
      Description: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest."
    },
    {
      Id: 23,
      Name: "Ekans",
      Type1: "Poison",
      Type2: "",
      HP: 35,
      Attack: 60,
      Defense: 44,
      Speed: 55,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ekans.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ekans.png",
      Description: "Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole."
    },
    {
      Id: 24,
      Name: "Arbok",
      Type1: "Poison",
      Type2: "",
      HP: 60,
      Attack: 85,
      Defense: 69,
      Speed: 80,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/arbok.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/arbok.png",
      Description: "It is rumored that the ferocious warning markings on its belly differ from area to area."
    },
    {
      Id: 25,
      Name: "Pikachu",
      Type1: "Electric",
      Type2: "",
      HP: 35,
      Attack: 55,
      Defense: 30,
      Speed: 90,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pikachu.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pikachu.png",
      Description: "When several of these Pokemon gather, their electricity could build and cause lightning storms."
    },
    {
      Id: 26,
      Name: "Raichu",
      Type1: "Electric",
      Type2: "",
      HP: 60,
      Attack: 90,
      Defense: 55,
      Speed: 100,
      Special: 90,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/raichu.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/raichu.png",
      Description: "Its long tail serves as a ground to protect itself from its own high voltage power."
    },
    {
      Id: 27,
      Name: "Sandshrew",
      Type1: "Ground",
      Type2: "",
      HP: 50,
      Attack: 75,
      Defense: 85,
      Speed: 40,
      Special: 30,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/sandshrew.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/sandshrew.png",
      Description: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food."
    },
    {
      Id: 28,
      Name: "Sandslash",
      Type1: "Ground",
      Type2: "",
      HP: 75,
      Attack: 100,
      Defense: 110,
      Speed: 65,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/sandslash.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/sandslash.png",
      Description: "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape."
    },
    {
      Id: 29,
      Name: "NidoranF",
      Type1: "Poison",
      Type2: "",
      HP: 55,
      Attack: 47,
      Defense: 52,
      Speed: 41,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidoranf.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidoranf.png",
      Description: "Although small, its venomous barbs render this Pokemon dangerous. The female has smaller horns."
    },
    {
      Id: 30,
      Name: "Nidorina",
      Type1: "Poison",
      Type2: "",
      HP: 70,
      Attack: 62,
      Defense: 67,
      Speed: 56,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidorina.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidorina.png",
      Description: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting."
    },
    {
      Id: 31,
      Name: "Nidoqueen",
      Type1: "Poison",
      Type2: "Ground",
      HP: 90,
      Attack: 82,
      Defense: 87,
      Speed: 76,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidoqueen.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidoqueen.png",
      Description: "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves."
    },
    {
      Id: 32,
      Name: "NidoranM",
      Type1: "Poison",
      Type2: "",
      HP: 46,
      Attack: 57,
      Defense: 40,
      Speed: 50,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidoranm.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidoranm.png",
      Description: "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom."
    },
    {
      Id: 33,
      Name: "Nidorino",
      Type1: "Poison",
      Type2: "",
      HP: 61,
      Attack: 72,
      Defense: 57,
      Speed: 65,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidorino.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidorino.png",
      Description: "An aggressive Pokemon that is quick to attack. The horn on its head secretes a powerful venom."
    },
    {
      Id: 34,
      Name: "Nidoking",
      Type1: "Poison",
      Type2: "Ground",
      HP: 81,
      Attack: 92,
      Defense: 77,
      Speed: 85,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidoking.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidoking.png",
      Description: "It uses its powerful tail in battle to smash, constrict, then break the prey's bones."
    },
    {
      Id: 35,
      Name: "Clefairy",
      Type1: "Normal",
      Type2: "",
      HP: 70,
      Attack: 45,
      Defense: 48,
      Speed: 35,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/clefairy.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/clefairy.png",
      Description: "Its magical and cute appeal has many admirers. It is rare and found only in certain areas."
    },
    {
      Id: 36,
      Name: "Clefable",
      Type1: "Normal",
      Type2: "",
      HP: 95,
      Attack: 70,
      Defense: 73,
      Speed: 60,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/clefable.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/clefable.png",
      Description: "A timid fairy Pokemon that is rarely seen. It will run and hide the moment it senses people."
    },
    {
      Id: 37,
      Name: "Vulpix",
      Type1: "Fire",
      Type2: "",
      HP: 38,
      Attack: 41,
      Defense: 40,
      Speed: 65,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/vulpix.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/vulpix.png",
      Description: "At the time of birth, it has just one tail. The tail splits from its tip as it grows older."
    },
    {
      Id: 38,
      Name: "Ninetales",
      Type1: "Fire",
      Type2: "",
      HP: 73,
      Attack: 76,
      Defense: 75,
      Speed: 100,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ninetales.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ninetales.png",
      Description: "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse."
    },
    {
      Id: 39,
      Name: "Jigglypuff",
      Type1: "Normal",
      Type2: "",
      HP: 115,
      Attack: 45,
      Defense: 20,
      Speed: 20,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/jigglypuff.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/jigglypuff.png",
      Description: "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep."
    },
    {
      Id: 40,
      Name: "Wigglytuff",
      Type1: "Normal",
      Type2: "",
      HP: 140,
      Attack: 70,
      Defense: 45,
      Speed: 45,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/wigglytuff.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/wigglytuff.png",
      Description: "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size."
    },
    {
      Id: 41,
      Name: "Zubat",
      Type1: "Poison",
      Type2: "Flying",
      HP: 40,
      Attack: 45,
      Defense: 35,
      Speed: 55,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/zubat.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/zubat.png",
      Description: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets."
    },
    {
      Id: 42,
      Name: "Golbat",
      Type1: "Poison",
      Type2: "Flying",
      HP: 75,
      Attack: 80,
      Defense: 70,
      Speed: 90,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/golbat.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/golbat.png",
      Description: "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly."
    },
    {
      Id: 43,
      Name: "Oddish",
      Type1: "Grass",
      Type2: "Poison",
      HP: 45,
      Attack: 50,
      Defense: 55,
      Speed: 30,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/oddish.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/oddish.png",
      Description: "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds."
    },
    {
      Id: 44,
      Name: "Gloom",
      Type1: "Grass",
      Type2: "Poison",
      HP: 60,
      Attack: 65,
      Defense: 70,
      Speed: 40,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/gloom.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/gloom.png",
      Description: "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey."
    },
    {
      Id: 45,
      Name: "Vileplume",
      Type1: "Grass",
      Type2: "Poison",
      HP: 75,
      Attack: 80,
      Defense: 85,
      Speed: 50,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/vileplume.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/vileplume.png",
      Description: "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up."
    },
    {
      Id: 46,
      Name: "Paras",
      Type1: "Bug",
      Type2: "Grass",
      HP: 35,
      Attack: 70,
      Defense: 55,
      Speed: 25,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/paras.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/paras.png",
      Description: "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host."
    },
    {
      Id: 47,
      Name: "Parasect",
      Type1: "Bug",
      Type2: "Grass",
      HP: 60,
      Attack: 95,
      Defense: 80,
      Speed: 30,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/parasect.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/parasect.png",
      Description: "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places."
    },
    {
      Id: 48,
      Name: "Venonat",
      Type1: "Bug",
      Type2: "Poison",
      HP: 60,
      Attack: 55,
      Defense: 50,
      Speed: 45,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/venonat.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/venonat.png",
      Description: "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night."
    },
    {
      Id: 49,
      Name: "Venomoth",
      Type1: "Bug",
      Type2: "Poison",
      HP: 70,
      Attack: 65,
      Defense: 60,
      Speed: 90,
      Special: 90,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/venomoth.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/venomoth.png",
      Description: "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has."
    },
    {
      Id: 50,
      Name: "Diglett",
      Type1: "Ground",
      Type2: "",
      HP: 10,
      Attack: 55,
      Defense: 25,
      Speed: 95,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/diglett.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/diglett.png",
      Description: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground."
    },
    {
      Id: 51,
      Name: "Dugtrio",
      Type1: "Ground",
      Type2: "",
      HP: 35,
      Attack: 80,
      Defense: 50,
      Speed: 120,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dugtrio.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dugtrio.png",
      Description: "A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground."
    },
    {
      Id: 52,
      Name: "Meowth",
      Type1: "Normal",
      Type2: "",
      HP: 40,
      Attack: 45,
      Defense: 35,
      Speed: 90,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/meowth.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/meowth.png",
      Description: "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change."
    },
    {
      Id: 53,
      Name: "Persian",
      Type1: "Normal",
      Type2: "",
      HP: 65,
      Attack: 70,
      Defense: 60,
      Speed: 115,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/persian.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/persian.png",
      Description: "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness."
    },
    {
      Id: 54,
      Name: "Psyduck",
      Type1: "Water",
      Type2: "",
      HP: 50,
      Attack: 52,
      Defense: 48,
      Speed: 55,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/psyduck.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/psyduck.png",
      Description: "While lulling its enemies with its vacant look, this wily Pokemon will use psychokinetic powers."
    },
    {
      Id: 55,
      Name: "Golduck",
      Type1: "Water",
      Type2: "",
      HP: 80,
      Attack: 82,
      Defense: 78,
      Speed: 85,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/golduck.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/golduck.png",
      Description: "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa."
    },
    {
      Id: 56,
      Name: "Mankey",
      Type1: "Fighting",
      Type2: "",
      HP: 40,
      Attack: 80,
      Defense: 35,
      Speed: 70,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/mankey.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/mankey.png",
      Description: "Extremely quick to anger. It could be docile one moment then thrashing away the next instant."
    },
    {
      Id: 57,
      Name: "Primeape",
      Type1: "Fighting",
      Type2: "",
      HP: 65,
      Attack: 105,
      Defense: 60,
      Speed: 95,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/primeape.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/primeape.png",
      Description: "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught."
    },
    {
      Id: 58,
      Name: "Growlithe",
      Type1: "Fire",
      Type2: "",
      HP: 55,
      Attack: 70,
      Defense: 45,
      Speed: 60,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/growlithe.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/growlithe.png",
      Description: "Very protective of its territory. It will bark and bite to repel intruders from its space."
    },
    {
      Id: 59,
      Name: "Arcanine",
      Type1: "Fire",
      Type2: "",
      HP: 90,
      Attack: 110,
      Defense: 80,
      Speed: 95,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/arcanine.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/arcanine.png",
      Description: "A Pokemon that has been admired since the past for its beauty. It runs agilely as if on wings."
    },
    {
      Id: 60,
      Name: "Poliwag",
      Type1: "Water",
      Type2: "",
      HP: 40,
      Attack: 50,
      Defense: 40,
      Speed: 90,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/poliwag.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/poliwag.png",
      Description: "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand."
    },
    {
      Id: 61,
      Name: "Poliwhirl",
      Type1: "Water",
      Type2: "",
      HP: 65,
      Attack: 65,
      Defense: 65,
      Speed: 90,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/poliwhirl.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/poliwhirl.png",
      Description: "Capable of living in or out of water. When out of water, it sweats to keep its body slimy."
    },
    {
      Id: 62,
      Name: "Poliwrath",
      Type1: "Water",
      Type2: "Fighting",
      HP: 90,
      Attack: 85,
      Defense: 95,
      Speed: 70,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/poliwrath.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/poliwrath.png",
      Description: "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers."
    },
    {
      Id: 63,
      Name: "Abra",
      Type1: "Psychic",
      Type2: "",
      HP: 25,
      Attack: 20,
      Defense: 15,
      Speed: 90,
      Special: 105,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/abra.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/abra.png",
      Description: "Using its ability to read minds, it will identify impending danger and TELEPORT to safety."
    },
    {
      Id: 64,
      Name: "Kadabra",
      Type1: "Psychic",
      Type2: "",
      HP: 40,
      Attack: 35,
      Defense: 30,
      Speed: 105,
      Special: 120,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kadabra.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kadabra.png",
      Description: "It emits special alpha waves from its body that induce headaches just by being close by."
    },
    {
      Id: 65,
      Name: "Alakazam",
      Type1: "Psychic",
      Type2: "",
      HP: 55,
      Attack: 50,
      Defense: 45,
      Speed: 120,
      Special: 135,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/alakazam.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/alakazam.png",
      Description: "Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000."
    },
    {
      Id: 66,
      Name: "Machop",
      Type1: "Fighting",
      Type2: "",
      HP: 70,
      Attack: 80,
      Defense: 50,
      Speed: 35,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/machop.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/machop.png",
      Description: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger."
    },
    {
      Id: 67,
      Name: "Machoke",
      Type1: "Fighting",
      Type2: "",
      HP: 80,
      Attack: 100,
      Defense: 70,
      Speed: 45,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/machoke.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/machoke.png",
      Description: "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions."
    },
    {
      Id: 68,
      Name: "Machamp",
      Type1: "Fighting",
      Type2: "",
      HP: 90,
      Attack: 130,
      Defense: 80,
      Speed: 55,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/machamp.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/machamp.png",
      Description: "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon."
    },
    {
      Id: 69,
      Name: "Bellsprout",
      Type1: "Grass",
      Type2: "Poison",
      HP: 50,
      Attack: 75,
      Defense: 35,
      Speed: 40,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/bellsprout.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/bellsprout.png",
      Description: "A carnivorous Pokemon that traps and eats bugs. It uses its root feet to soak up needed moisture."
    },
    {
      Id: 70,
      Name: "Weepinbell",
      Type1: "Grass",
      Type2: "Poison",
      HP: 65,
      Attack: 90,
      Defense: 50,
      Speed: 55,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/weepinbell.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/weepinbell.png",
      Description: "It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID."
    },
    {
      Id: 71,
      Name: "Victreebel",
      Type1: "Grass",
      Type2: "Poison",
      HP: 80,
      Attack: 105,
      Defense: 65,
      Speed: 70,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/victreebel.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/victreebel.png",
      Description: "Said to live in huge colonies deep in jungles, although no one has ever returned from there."
    },
    {
      Id: 72,
      Name: "Tentacool",
      Type1: "Water",
      Type2: "Poison",
      HP: 40,
      Attack: 40,
      Defense: 35,
      Speed: 70,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/tentacool.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/tentacool.png",
      Description: "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid."
    },
    {
      Id: 73,
      Name: "Tentacruel",
      Type1: "Water",
      Type2: "Poison",
      HP: 80,
      Attack: 70,
      Defense: 65,
      Speed: 100,
      Special: 120,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/tentacruel.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/tentacruel.png",
      Description: "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey."
    },
    {
      Id: 74,
      Name: "Geodude",
      Type1: "Rock",
      Type2: "Ground",
      HP: 40,
      Attack: 80,
      Defense: 100,
      Speed: 20,
      Special: 30,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/geodude.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/geodude.png",
      Description: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them."
    },
    {
      Id: 75,
      Name: "Graveler",
      Type1: "Rock",
      Type2: "Ground",
      HP: 55,
      Attack: 95,
      Defense: 115,
      Speed: 35,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/graveler.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/graveler.png",
      Description: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction."
    },
    {
      Id: 76,
      Name: "Golem",
      Type1: "Rock",
      Type2: "Ground",
      HP: 80,
      Attack: 110,
      Defense: 130,
      Speed: 45,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/golem.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/golem.png",
      Description: "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage."
    },
    {
      Id: 77,
      Name: "Ponyta",
      Type1: "Fire",
      Type2: "",
      HP: 50,
      Attack: 85,
      Defense: 55,
      Speed: 90,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ponyta.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ponyta.png",
      Description: "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time."
    },
    {
      Id: 78,
      Name: "Rapidash",
      Type1: "Fire",
      Type2: "",
      HP: 65,
      Attack: 100,
      Defense: 70,
      Speed: 105,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/rapidash.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/rapidash.png",
      Description: "Very competitive, this Pokemon will chase anything that moves fast in the hopes of racing it."
    },
    {
      Id: 79,
      Name: "Slowpoke",
      Type1: "Water",
      Type2: "Psychic",
      HP: 90,
      Attack: 65,
      Defense: 65,
      Speed: 15,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/slowpoke.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/slowpoke.png",
      Description: "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack."
    },
    {
      Id: 80,
      Name: "Slowbro",
      Type1: "Water",
      Type2: "Psychic",
      HP: 95,
      Attack: 75,
      Defense: 110,
      Speed: 30,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/slowbro.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/slowbro.png",
      Description: "The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps."
    },
    {
      Id: 81,
      Name: "Magnemite",
      Type1: "Electric",
      Type2: "",
      HP: 25,
      Attack: 35,
      Defense: 70,
      Speed: 45,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/magnemite.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/magnemite.png",
      Description: "Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves."
    },
    {
      Id: 82,
      Name: "Magneton",
      Type1: "Electric",
      Type2: "",
      HP: 50,
      Attack: 60,
      Defense: 95,
      Speed: 70,
      Special: 120,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/magneton.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/magneton.png",
      Description: "Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up."
    },
    {
      Id: 83,
      Name: "Farfetch'd",
      Type1: "Normal",
      Type2: "Flying",
      HP: 52,
      Attack: 65,
      Defense: 55,
      Speed: 60,
      Special: 58,
      GIF: "http://play.pokemonshowdown.com/sprites/bwani/farfetchd.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/farfetchd.png",
      Description: "The sprig of green onions it holds is its weapon. It is used much like a metal sword."
    },
    {
      Id: 84,
      Name: "Doduo",
      Type1: "Normal",
      Type2: "Flying",
      HP: 35,
      Attack: 85,
      Defense: 45,
      Speed: 75,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/doduo.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/doduo.png",
      Description: "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints."
    },
    {
      Id: 85,
      Name: "Dodrio",
      Type1: "Normal",
      Type2: "Flying",
      HP: 60,
      Attack: 110,
      Defense: 70,
      Speed: 100,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dodrio.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dodrio.png",
      Description: "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake."
    },
    {
      Id: 86,
      Name: "Seel",
      Type1: "Water",
      Type2: "",
      HP: 65,
      Attack: 45,
      Defense: 55,
      Speed: 45,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/seel.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/seel.png",
      Description: "The protruding horn on its head is very hard. It is used for bashing through thick ice."
    },
    {
      Id: 87,
      Name: "Dewgong",
      Type1: "Water",
      Type2: "Ice",
      HP: 90,
      Attack: 70,
      Defense: 80,
      Speed: 70,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dewgong.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dewgong.png",
      Description: "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters."
    },
    {
      Id: 88,
      Name: "Grimer",
      Type1: "Poison",
      Type2: "",
      HP: 80,
      Attack: 80,
      Defense: 50,
      Speed: 25,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/grimer.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/grimer.png",
      Description: "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories."
    },
    {
      Id: 89,
      Name: "Muk",
      Type1: "Poison",
      Type2: "",
      HP: 105,
      Attack: 105,
      Defense: 75,
      Speed: 50,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/muk.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/muk.png",
      Description: "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison."
    },
    {
      Id: 90,
      Name: "Shellder",
      Type1: "Water",
      Type2: "",
      HP: 30,
      Attack: 65,
      Defense: 100,
      Speed: 40,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/shellder.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/shellder.png",
      Description: "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open."
    },
    {
      Id: 91,
      Name: "Cloyster",
      Type1: "Water",
      Type2: "Ice",
      HP: 50,
      Attack: 95,
      Defense: 180,
      Speed: 70,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/cloyster.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/cloyster.png",
      Description: "When attacked, it launches its horns in quick volleys. Its innards have never been seen."
    },
    {
      Id: 92,
      Name: "Gastly",
      Type1: "Ghost",
      Type2: "Poison",
      HP: 30,
      Attack: 35,
      Defense: 30,
      Speed: 80,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/gastly.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/gastly.png",
      Description: "Almost invisible, this gaseous Pokemon cloaks the target and puts it to sleep without notice."
    },
    {
      Id: 93,
      Name: "Haunter",
      Type1: "Ghost",
      Type2: "Poison",
      HP: 45,
      Attack: 50,
      Defense: 45,
      Speed: 95,
      Special: 115,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/haunter.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/haunter.png",
      Description: "Because of its ability to slip through block walls, it is said to be from another dimension."
    },
    {
      Id: 94,
      Name: "Gengar",
      Type1: "Ghost",
      Type2: "Poison",
      HP: 60,
      Attack: 65,
      Defense: 60,
      Speed: 110,
      Special: 130,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/gengar.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/gengar.png",
      Description: "Under a full moon, this Pokemon likes to mimic the shadows of people and laugh at their fright."
    },
    {
      Id: 95,
      Name: "Onix",
      Type1: "Rock",
      Type2: "Ground",
      HP: 35,
      Attack: 45,
      Defense: 160,
      Speed: 70,
      Special: 30,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/onix.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/onix.png",
      Description: "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black."
    },
    {
      Id: 96,
      Name: "Drowzee",
      Type1: "Psychic",
      Type2: "",
      HP: 60,
      Attack: 48,
      Defense: 45,
      Speed: 42,
      Special: 90,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/drowzee.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/drowzee.png",
      Description: "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams."
    },
    {
      Id: 97,
      Name: "Hypno",
      Type1: "Psychic",
      Type2: "",
      HP: 85,
      Attack: 73,
      Defense: 70,
      Speed: 67,
      Special: 115,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/hypno.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/hypno.png",
      Description: "When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION."
    },
    {
      Id: 98,
      Name: "Krabby",
      Type1: "Water",
      Type2: "",
      HP: 30,
      Attack: 105,
      Defense: 90,
      Speed: 50,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/krabby.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/krabby.png",
      Description: "Its pincers are not only powerful weapons, they are used for balance when walking sideways."
    },
    {
      Id: 99,
      Name: "Kingler",
      Type1: "Water",
      Type2: "",
      HP: 55,
      Attack: 130,
      Defense: 115,
      Speed: 75,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kingler.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kingler.png",
      Description: "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use."
    },
    {
      Id: 100,
      Name: "Voltorb",
      Type1: "Electric",
      Type2: "",
      HP: 40,
      Attack: 30,
      Defense: 50,
      Speed: 100,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/voltorb.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/voltorb.png",
      Description: "Usually found in power plants. Easily mistaken for a Pokeball, they have zapped many people."
    },
    {
      Id: 101,
      Name: "Electrode",
      Type1: "Electric",
      Type2: "",
      HP: 60,
      Attack: 50,
      Defense: 70,
      Speed: 140,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/electrode.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/electrode.png",
      Description: "It stores electric energy under very high pressure. It often explodes with little or no provocation."
    },
    {
      Id: 102,
      Name: "Exeggcute",
      Type1: "Grass",
      Type2: "Psychic",
      HP: 60,
      Attack: 40,
      Defense: 80,
      Speed: 40,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/exeggcute.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/exeggcute.png",
      Description: "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms."
    },
    {
      Id: 103,
      Name: "Exeggutor",
      Type1: "Grass",
      Type2: "Psychic",
      HP: 95,
      Attack: 95,
      Defense: 85,
      Speed: 55,
      Special: 125,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/exeggutor.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/exeggutor.png",
      Description: "Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE."
    },
    {
      Id: 104,
      Name: "Cubone",
      Type1: "Ground",
      Type2: "",
      HP: 50,
      Attack: 50,
      Defense: 95,
      Speed: 35,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/cubone.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/cubone.png",
      Description: "Because it never removes its skull helmet, no one has ever seen this Pokemon's real face."
    },
    {
      Id: 105,
      Name: "Marowak",
      Type1: "Ground",
      Type2: "",
      HP: 60,
      Attack: 80,
      Defense: 110,
      Speed: 45,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/marowak.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/marowak.png",
      Description: "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets."
    },
    {
      Id: 106,
      Name: "Hitmonlee",
      Type1: "Fighting",
      Type2: "",
      HP: 50,
      Attack: 120,
      Defense: 53,
      Speed: 87,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/hitmonlee.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/hitmonlee.png",
      Description: "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides."
    },
    {
      Id: 107,
      Name: "Hitmonchan",
      Type1: "Fighting",
      Type2: "",
      HP: 50,
      Attack: 105,
      Defense: 79,
      Speed: 76,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/hitmonchan.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/hitmonchan.png",
      Description: "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see."
    },
    {
      Id: 108,
      Name: "Lickitung",
      Type1: "Normal",
      Type2: "",
      HP: 90,
      Attack: 55,
      Defense: 75,
      Speed: 30,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/lickitung.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/lickitung.png",
      Description: "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies."
    },
    {
      Id: 109,
      Name: "Koffing",
      Type1: "Poison",
      Type2: "",
      HP: 40,
      Attack: 65,
      Defense: 95,
      Speed: 35,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/koffing.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/koffing.png",
      Description: "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning."
    },
    {
      Id: 110,
      Name: "Weezing",
      Type1: "Poison",
      Type2: "",
      HP: 65,
      Attack: 90,
      Defense: 120,
      Speed: 60,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/weezing.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/weezing.png",
      Description: "Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years."
    },
    {
      Id: 111,
      Name: "Rhyhorn",
      Type1: "Ground",
      Type2: "Rock",
      HP: 80,
      Attack: 85,
      Defense: 95,
      Speed: 25,
      Special: 30,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/rhyhorn.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/rhyhorn.png",
      Description: "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying."
    },
    {
      Id: 112,
      Name: "Rhydon",
      Type1: "Ground",
      Type2: "Rock",
      HP: 105,
      Attack: 130,
      Defense: 120,
      Speed: 40,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/rhydon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/rhydon.png",
      Description: "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees."
    },
    {
      Id: 113,
      Name: "Chansey",
      Type1: "Normal",
      Type2: "",
      HP: 250,
      Attack: 5,
      Defense: 5,
      Speed: 50,
      Special: 105,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/chansey.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/chansey.png",
      Description: "A rare and elusive Pokemon that is said to bring happiness to those who manage to get it."
    },
    {
      Id: 114,
      Name: "Tangela",
      Type1: "Grass",
      Type2: "",
      HP: 65,
      Attack: 55,
      Defense: 115,
      Speed: 60,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/tangela.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/tangela.png",
      Description: "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks."
    },
    {
      Id: 115,
      Name: "Kangaskhan",
      Type1: "Normal",
      Type2: "",
      HP: 105,
      Attack: 95,
      Defense: 80,
      Speed: 90,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kangaskhan.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kangaskhan.png",
      Description: "The infant rarely ventures out of its mother's protective pouch until it is 3 years old."
    },
    {
      Id: 116,
      Name: "Horsea",
      Type1: "Water",
      Type2: "",
      HP: 30,
      Attack: 40,
      Defense: 70,
      Speed: 60,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/horsea.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/horsea.png",
      Description: "Known to shoot down flying bugs with precision blasts of ink from the surface of the water."
    },
    {
      Id: 117,
      Name: "Seadra",
      Type1: "Water",
      Type2: "",
      HP: 55,
      Attack: 65,
      Defense: 95,
      Speed: 85,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/seadra.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/seadra.png",
      Description: "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail."
    },
    {
      Id: 118,
      Name: "Goldeen",
      Type1: "Water",
      Type2: "",
      HP: 45,
      Attack: 67,
      Defense: 60,
      Speed: 63,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/goldeen.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/goldeen.png",
      Description: "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen."
    },
    {
      Id: 119,
      Name: "Seaking",
      Type1: "Water",
      Type2: "",
      HP: 80,
      Attack: 92,
      Defense: 65,
      Speed: 68,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/seaking.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/seaking.png",
      Description: "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks."
    },
    {
      Id: 120,
      Name: "Staryu",
      Type1: "Water",
      Type2: "",
      HP: 30,
      Attack: 45,
      Defense: 55,
      Speed: 85,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/staryu.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/staryu.png",
      Description: "An enigmatic Pokemon that can effortlessly regenerate any appendage it loses in battle."
    },
    {
      Id: 121,
      Name: "Starmie",
      Type1: "Water",
      Type2: "Psychic",
      HP: 60,
      Attack: 75,
      Defense: 85,
      Speed: 115,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/starmie.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/starmie.png",
      Description: "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem."
    },
    {
      Id: 122,
      Name: "Mr. Mime",
      Type1: "Psychic",
      Type2: "",
      HP: 40,
      Attack: 45,
      Defense: 65,
      Speed: 90,
      Special: 100,
      GIF: "http://play.pokemonshowdown.com/sprites/bwani/mrmime.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/mrmime.png",
      Description: "If interrupted while it is miming, it will slap around the offender with its broad hands."
    },
    {
      Id: 123,
      Name: "Scyther",
      Type1: "Bug",
      Type2: "Flying",
      HP: 70,
      Attack: 110,
      Defense: 80,
      Speed: 105,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/scyther.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/scyther.png",
      Description: "With ninja-like agility and speed, it can create the illusion that there is more than one."
    },
    {
      Id: 124,
      Name: "Jynx",
      Type1: "Ice",
      Type2: "Psychic",
      HP: 65,
      Attack: 50,
      Defense: 35,
      Speed: 95,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/jynx.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/jynx.png",
      Description: "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it."
    },
    {
      Id: 125,
      Name: "Electabuzz",
      Type1: "Electric",
      Type2: "",
      HP: 65,
      Attack: 83,
      Defense: 57,
      Speed: 105,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/electabuzz.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/electabuzz.png",
      Description: "Normally found near power plants, they can wander away and cause major blackouts in cities."
    },
    {
      Id: 126,
      Name: "Magmar",
      Type1: "Fire",
      Type2: "",
      HP: 65,
      Attack: 95,
      Defense: 57,
      Speed: 93,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/magmar.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/magmar.png",
      Description: "Its body always burns with an orange glow that enables it to hide perfectly among flames."
    },
    {
      Id: 127,
      Name: "Pinsir",
      Type1: "Bug",
      Type2: "",
      HP: 65,
      Attack: 125,
      Defense: 100,
      Speed: 85,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pinsir.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pinsir.png",
      Description: "If it fails to crush the victim in its pincers, it will swing it around and toss it hard."
    },
    {
      Id: 128,
      Name: "Tauros",
      Type1: "Normal",
      Type2: "",
      HP: 75,
      Attack: 100,
      Defense: 95,
      Speed: 110,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/tauros.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/tauros.png",
      Description: "When it targets an enemy, it charges furiously while whipping its body with its long tails."
    },
    {
      Id: 129,
      Name: "Magikarp",
      Type1: "Water",
      Type2: "",
      HP: 20,
      Attack: 10,
      Defense: 55,
      Speed: 80,
      Special: 20,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/magikarp.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/magikarp.png",
      Description: "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today."
    },
    {
      Id: 130,
      Name: "Gyarados",
      Type1: "Water",
      Type2: "Flying",
      HP: 95,
      Attack: 125,
      Defense: 79,
      Speed: 81,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/gyarados.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/gyarados.png",
      Description: "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage."
    },
    {
      Id: 131,
      Name: "Lapras",
      Type1: "Water",
      Type2: "Ice",
      HP: 130,
      Attack: 85,
      Defense: 80,
      Speed: 60,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/lapras.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/lapras.png",
      Description: "A Pokemon that has been overhunted almost to extinction. It can ferry people across the water."
    },
    {
      Id: 132,
      Name: "Ditto",
      Type1: "Normal",
      Type2: "",
      HP: 48,
      Attack: 48,
      Defense: 48,
      Speed: 48,
      Special: 48,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ditto.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ditto.png",
      Description: "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy."
    },
    {
      Id: 133,
      Name: "Eevee",
      Type1: "Normal",
      Type2: "",
      HP: 55,
      Attack: 55,
      Defense: 50,
      Speed: 55,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/eevee.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/eevee.png",
      Description: "Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs."
    },
    {
      Id: 134,
      Name: "Vaporeon",
      Type1: "Water",
      Type2: "",
      HP: 130,
      Attack: 65,
      Defense: 60,
      Speed: 65,
      Special: 110,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/vaporeon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/vaporeon.png",
      Description: "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's."
    },
    {
      Id: 135,
      Name: "Jolteon",
      Type1: "Electric",
      Type2: "",
      HP: 65,
      Attack: 65,
      Defense: 60,
      Speed: 130,
      Special: 110,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/jolteon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/jolteon.png",
      Description: "It accumulates negative ions in the atmosphere to blast out 10000- volt lightning bolts."
    },
    {
      Id: 136,
      Name: "Flareon",
      Type1: "Fire",
      Type2: "",
      HP: 65,
      Attack: 130,
      Defense: 60,
      Speed: 65,
      Special: 110,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/flareon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/flareon.png",
      Description: "When storing thermal energy in its body, its temperature could soar to over 1600 degrees."
    },
    {
      Id: 137,
      Name: "Porygon",
      Type1: "Normal",
      Type2: "",
      HP: 65,
      Attack: 60,
      Defense: 70,
      Speed: 40,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/porygon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/porygon.png",
      Description: "A Pokemon that consists entirely of programming code. Capable of moving freely in cyberspace."
    },
    {
      Id: 138,
      Name: "Omanyte",
      Type1: "Rock",
      Type2: "Water",
      HP: 35,
      Attack: 40,
      Defense: 100,
      Speed: 35,
      Special: 90,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/omanyte.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/omanyte.png",
      Description: "Although long extinct, in rare cases, it can be genetically resurrected from fossils."
    },
    {
      Id: 139,
      Name: "Omastar",
      Type1: "Rock",
      Type2: "Water",
      HP: 70,
      Attack: 60,
      Defense: 125,
      Speed: 55,
      Special: 115,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/omastar.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/omastar.png",
      Description: "A prehistoric Pokemon that died out when its heavy shell made it impossible to catch prey."
    },
    {
      Id: 140,
      Name: "Kabuto",
      Type1: "Rock",
      Type2: "Water",
      HP: 30,
      Attack: 80,
      Defense: 90,
      Speed: 55,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kabuto.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kabuto.png",
      Description: "A Pokemon that was resurrected from a fossil found in what was once the ocean floor eons ago."
    },
    {
      Id: 141,
      Name: "Kabutops",
      Type1: "Rock",
      Type2: "Water",
      HP: 60,
      Attack: 115,
      Defense: 105,
      Speed: 80,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kabutops.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kabutops.png",
      Description: "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids."
    },
    {
      Id: 142,
      Name: "Aerodactyl",
      Type1: "Rock",
      Type2: "Flying",
      HP: 80,
      Attack: 105,
      Defense: 65,
      Speed: 130,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/aerodactyl.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/aerodactyl.png",
      Description: "A ferocious, prehistoric Pokemon that goes for the enemy's throat with its serrated saw-like fangs."
    },
    {
      Id: 143,
      Name: "Snorlax",
      Type1: "Normal",
      Type2: "",
      HP: 160,
      Attack: 110,
      Defense: 65,
      Speed: 30,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/snorlax.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/snorlax.png",
      Description: "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful."
    },
    {
      Id: 144,
      Name: "Articuno",
      Type1: "Ice",
      Type2: "Flying",
      HP: 90,
      Attack: 85,
      Defense: 100,
      Speed: 85,
      Special: 125,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/articuno.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/articuno.png",
      Description: "A legendary bird Pokemon that is said to appear to doomed people who are lost in icy mountains."
    },
    {
      Id: 145,
      Name: "Zapdos",
      Type1: "Electric",
      Type2: "Flying",
      HP: 90,
      Attack: 90,
      Defense: 85,
      Speed: 100,
      Special: 125,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/zapdos.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/zapdos.png",
      Description: "A legendary bird Pokemon that is said to appear from clouds while dropping enormous lightning bolts."
    },
    {
      Id: 146,
      Name: "Moltres",
      Type1: "Fire",
      Type2: "Flying",
      HP: 90,
      Attack: 100,
      Defense: 90,
      Speed: 90,
      Special: 125,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/moltres.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/moltres.png",
      Description: "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames."
    },
    {
      Id: 147,
      Name: "Dratini",
      Type1: "Dragon",
      Type2: "",
      HP: 41,
      Attack: 64,
      Defense: 45,
      Speed: 50,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dratini.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dratini.png",
      Description: "Long considered a mythical Pokemon until recently when a small colony was found living underwater."
    },
    {
      Id: 148,
      Name: "Dragonair",
      Type1: "Dragon",
      Type2: "",
      HP: 61,
      Attack: 84,
      Defense: 65,
      Speed: 70,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dragonair.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dragonair.png",
      Description: "A mystical Pokemon that exudes a gentle aura. Has the ability to change climate conditions."
    },
    {
      Id: 149,
      Name: "Dragonite",
      Type1: "Dragon",
      Type2: "Flying",
      HP: 91,
      Attack: 134,
      Defense: 95,
      Speed: 80,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dragonite.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dragonite.png",
      Description: "An extremely rarely seen marine Pokemon. Its intelligence is said to match that of humans."
    },
    {
      Id: 150,
      Name: "Mewtwo",
      Type1: "Psychic",
      Type2: "",
      HP: 106,
      Attack: 110,
      Defense: 90,
      Speed: 130,
      Special: 154,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/mewtwo.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/mewtwo.png",
      Description: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments."
    },
    {
      Id: 151,
      Name: "Mew",
      Type1: "Psychic",
      Type2: "",
      HP: 100,
      Attack: 100,
      Defense: 100,
      Speed: 100,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/mew.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/mew.png",
      Description: "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide."
    }
];
