import { Pokemon } from "./pokemon";

export const POKEMONS: Pokemon[] = [
    {
      id: 1,
      name: "Bulbasaur",
      types: ["Grass", "Poison"],
      hp: 45,
      cp: 49,
      def: 49,
      Speed: 45,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/bulbasaur.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/bulbasaur.png",
      Description: "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokemon."
    },
    {
      id: 2,
      name: "Ivysaur",
      types: ["Grass", "Poison"],
      hp: 60,
      cp: 62,
      def: 63,
      Speed: 60,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ivysaur.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ivysaur.png",
      Description: "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa."
    },
    {
      id: 3,
      name: "Venusaur",
      types: ["Grass", "Poison"],
      hp: 80,
      cp: 82,
      def: 83,
      Speed: 80,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/venusaur.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/venusaur.png",
      Description: "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning."
    },
    {
      id: 4,
      name: "Charmander",
      types: ["Fire", ""],
      hp: 39,
      cp: 52,
      def: 43,
      Speed: 65,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/charmander.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/charmander.png",
      Description: "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail."
    },
    {
      id: 5,
      name: "Charmeleon",
      types: ["Fire", ""],
      hp: 58,
      cp: 64,
      def: 58,
      Speed: 80,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/charmeleon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/charmeleon.png",
      Description: "When it swings its burning tail, it elevates the temperature to unbearably high levels."
    },
    {
      id: 6,
      name: "Charizard",
      types: ["Fire", "Flying"],
      hp: 78,
      cp: 84,
      def: 78,
      Speed: 100,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/charizard.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/charizard.png",
      Description: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally."
    },
    {
      id: 7,
      name: "Squirtle",
      types: ["Water", ""],
      hp: 44,
      cp: 48,
      def: 65,
      Speed: 43,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/squirtle.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/squirtle.png",
      Description: "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth."
    },
    {
      id: 8,
      name: "Wartortle",
      types: ["Water", ""],
      hp: 59,
      cp: 63,
      def: 80,
      Speed: 58,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/wartortle.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/wartortle.png",
      Description: "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance."
    },
    {
      id: 9,
      name: "Blastoise",
      types: ["Water", ""],
      hp: 79,
      cp: 83,
      def: 100,
      Speed: 78,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/blastoise.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/blastoise.png",
      Description: "A brutal Pokemon with pressurized water jets on its shell. They are used for high speed tackles."
    },
    {
      id: 10,
      name: "Caterpie",
      types: ["Bug", ""],
      hp: 45,
      cp: 30,
      def: 35,
      Speed: 45,
      Special: 20,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/caterpie.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/caterpie.png",
      Description: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls."
    },
    {
      id: 11,
      name: "Metapod",
      types: ["Bug", ""],
      hp: 50,
      cp: 20,
      def: 55,
      Speed: 30,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/metapod.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/metapod.png",
      Description: "This Pokemon is vulnerable to attack while its shell is soft, exposing its weak and tender body."
    },
    {
      id: 12,
      name: "Butterfree",
      types: ["Bug", "Flying"],
      hp: 60,
      cp: 45,
      def: 50,
      Speed: 70,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/butterfree.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/butterfree.png",
      Description: "In battle, it flaps its wings at high speed to release highly toxic dust into the air."
    },
    {
      id: 13,
      name: "Weedle",
      types: ["Bug", "Poison"],
      hp: 40,
      cp: 35,
      def: 30,
      Speed: 50,
      Special: 20,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/weedle.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/weedle.png",
      Description: "Often found in forests, eating leaves. It has a sharp venomous stinger on its head."
    },
    {
      id: 14,
      name: "Kakuna",
      types: ["Bug", "Poison"],
      hp: 45,
      cp: 25,
      def: 50,
      Speed: 35,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kakuna.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kakuna.png",
      Description: "Almost incapable of moving, this Pokemon can only harden its shell to protect itself from predators."
    },
    {
      id: 15,
      name: "Beedrill",
      types: ["Bug", "Poison"],
      hp: 65,
      cp: 80,
      def: 40,
      Speed: 75,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/beedrill.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/beedrill.png",
      Description: "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail."
    },
    {
      id: 16,
      name: "Pidgey",
      types: ["Normal", "Flying"],
      hp: 40,
      cp: 45,
      def: 40,
      Speed: 56,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pidgey.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pidgey.png",
      Description: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand."
    },
    {
      id: 17,
      name: "Pidgeotto",
      types: ["Normal", "Flying"],
      hp: 63,
      cp: 60,
      def: 55,
      Speed: 71,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pidgeotto.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pidgeotto.png",
      Description: "Very protective of its sprawling territorial area, this Pokemon will fiercely peck at any intruder."
    },
    {
      id: 18,
      name: "Pidgeot",
      types: ["Normal", "Flying"],
      hp: 83,
      cp: 80,
      def: 75,
      Speed: 91,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pidgeot.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pidgeot.png",
      Description: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP."
    },
    {
      id: 19,
      name: "Rattata",
      types: ["Normal", ""],
      hp: 30,
      cp: 56,
      def: 35,
      Speed: 72,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/rattata.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/rattata.png",
      Description: "Bites anything when it attacks. Small and very quick, it is a common sight in many places."
    },
    {
      id: 20,
      name: "Raticate",
      types: ["Normal", ""],
      hp: 55,
      cp: 81,
      def: 60,
      Speed: 97,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/raticate.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/raticate.png",
      Description: "It uses its whiskers to maintain its balance. It apparently slows down if they are cut off."
    },
    {
      id: 21,
      name: "Spearow",
      types: ["Normal", "Flying"],
      hp: 40,
      cp: 60,
      def: 30,
      Speed: 70,
      Special: 31,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/spearow.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/spearow.png",
      Description: "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne."
    },
    {
      id: 22,
      name: "Fearow",
      types: ["Normal", "Flying"],
      hp: 65,
      cp: 90,
      def: 65,
      Speed: 100,
      Special: 61,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/fearow.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/fearow.png",
      Description: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest."
    },
    {
      id: 23,
      name: "Ekans",
      types: ["Poison", ""],
      hp: 35,
      cp: 60,
      def: 44,
      Speed: 55,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ekans.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ekans.png",
      Description: "Moves silently and stealthily. Eats the eggs of birds, such as PidGEY and SPEAROW, whole."
    },
    {
      id: 24,
      name: "Arbok",
      types: ["Poison", ""],
      hp: 60,
      cp: 85,
      def: 69,
      Speed: 80,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/arbok.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/arbok.png",
      Description: "It is rumored that the ferocious warning markings on its belly differ from area to area."
    },
    {
      id: 25,
      name: "Pikachu",
      types: ["Electric", ""],
      hp: 35,
      cp: 55,
      def: 30,
      Speed: 90,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pikachu.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pikachu.png",
      Description: "When several of these Pokemon gather, their electricity could build and cause lightning storms."
    },
    {
      id: 26,
      name: "Raichu",
      types: ["Electric", ""],
      hp: 60,
      cp: 90,
      def: 55,
      Speed: 100,
      Special: 90,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/raichu.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/raichu.png",
      Description: "Its long tail serves as a ground to protect itself from its own high voltage power."
    },
    {
      id: 27,
      name: "Sandshrew",
      types: ["Ground", ""],
      hp: 50,
      cp: 75,
      def: 85,
      Speed: 40,
      Special: 30,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/sandshrew.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/sandshrew.png",
      Description: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food."
    },
    {
      id: 28,
      name: "Sandslash",
      types: ["Ground", ""],
      hp: 75,
      cp: 100,
      def: 110,
      Speed: 65,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/sandslash.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/sandslash.png",
      Description: "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape."
    },
    {
      id: 29,
      name: "NidoranF",
      types: ["Poison", ""],
      hp: 55,
      cp: 47,
      def: 52,
      Speed: 41,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidoranf.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidoranf.png",
      Description: "Although small, its venomous barbs render this Pokemon dangerous. The female has smaller horns."
    },
    {
      id: 30,
      name: "Nidorina",
      types: ["Poison", ""],
      hp: 70,
      cp: 62,
      def: 67,
      Speed: 56,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidorina.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidorina.png",
      Description: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting."
    },
    {
      id: 31,
      name: "Nidoqueen",
      types: ["Poison", "Ground"],
      hp: 90,
      cp: 82,
      def: 87,
      Speed: 76,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidoqueen.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidoqueen.png",
      Description: "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves."
    },
    {
      id: 32,
      name: "NidoranM",
      types: ["Poison", ""],
      hp: 46,
      cp: 57,
      def: 40,
      Speed: 50,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidoranm.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidoranm.png",
      Description: "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom."
    },
    {
      id: 33,
      name: "Nidorino",
      types: ["Poison", ""],
      hp: 61,
      cp: 72,
      def: 57,
      Speed: 65,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidorino.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidorino.png",
      Description: "An aggressive Pokemon that is quick to attack. The horn on its head secretes a powerful venom."
    },
    {
      id: 34,
      name: "Nidoking",
      types: ["Poison", "Ground"],
      hp: 81,
      cp: 92,
      def: 77,
      Speed: 85,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/nidoking.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/nidoking.png",
      Description: "It uses its powerful tail in battle to smash, constrict, then break the prey's bones."
    },
    {
      id: 35,
      name: "Clefairy",
      types: ["Normal", ""],
      hp: 70,
      cp: 45,
      def: 48,
      Speed: 35,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/clefairy.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/clefairy.png",
      Description: "Its magical and cute appeal has many admirers. It is rare and found only in certain areas."
    },
    {
      id: 36,
      name: "Clefable",
      types: ["Normal", ""],
      hp: 95,
      cp: 70,
      def: 73,
      Speed: 60,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/clefable.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/clefable.png",
      Description: "A timid fairy Pokemon that is rarely seen. It will run and hide the moment it senses people."
    },
    {
      id: 37,
      name: "Vulpix",
      types: ["Fire", ""],
      hp: 38,
      cp: 41,
      def: 40,
      Speed: 65,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/vulpix.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/vulpix.png",
      Description: "At the time of birth, it has just one tail. The tail splits from its tip as it grows older."
    },
    {
      id: 38,
      name: "Ninetales",
      types: ["Fire", ""],
      hp: 73,
      cp: 76,
      def: 75,
      Speed: 100,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ninetales.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ninetales.png",
      Description: "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse."
    },
    {
      id: 39,
      name: "Jigglypuff",
      types: ["Normal", ""],
      hp: 115,
      cp: 45,
      def: 20,
      Speed: 20,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/jigglypuff.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/jigglypuff.png",
      Description: "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep."
    },
    {
      id: 40,
      name: "Wigglytuff",
      types: ["Normal", ""],
      hp: 140,
      cp: 70,
      def: 45,
      Speed: 45,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/wigglytuff.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/wigglytuff.png",
      Description: "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size."
    },
    {
      id: 41,
      name: "Zubat",
      types: ["Poison", "Flying"],
      hp: 40,
      cp: 45,
      def: 35,
      Speed: 55,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/zubat.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/zubat.png",
      Description: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets."
    },
    {
      id: 42,
      name: "Golbat",
      types: ["Poison", "Flying"],
      hp: 75,
      cp: 80,
      def: 70,
      Speed: 90,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/golbat.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/golbat.png",
      Description: "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly."
    },
    {
      id: 43,
      name: "Oddish",
      types: ["Grass", "Poison"],
      hp: 45,
      cp: 50,
      def: 55,
      Speed: 30,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/oddish.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/oddish.png",
      Description: "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds."
    },
    {
      id: 44,
      name: "Gloom",
      types: ["Grass", "Poison"],
      hp: 60,
      cp: 65,
      def: 70,
      Speed: 40,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/gloom.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/gloom.png",
      Description: "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey."
    },
    {
      id: 45,
      name: "Vileplume",
      types: ["Grass", "Poison"],
      hp: 75,
      cp: 80,
      def: 85,
      Speed: 50,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/vileplume.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/vileplume.png",
      Description: "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up."
    },
    {
      id: 46,
      name: "Paras",
      types: ["Bug", "Grass"],
      hp: 35,
      cp: 70,
      def: 55,
      Speed: 25,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/paras.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/paras.png",
      Description: "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host."
    },
    {
      id: 47,
      name: "Parasect",
      types: ["Bug", "Grass"],
      hp: 60,
      cp: 95,
      def: 80,
      Speed: 30,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/parasect.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/parasect.png",
      Description: "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places."
    },
    {
      id: 48,
      name: "Venonat",
      types: ["Bug", "Poison"],
      hp: 60,
      cp: 55,
      def: 50,
      Speed: 45,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/venonat.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/venonat.png",
      Description: "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night."
    },
    {
      id: 49,
      name: "Venomoth",
      types: ["Bug", "Poison"],
      hp: 70,
      cp: 65,
      def: 60,
      Speed: 90,
      Special: 90,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/venomoth.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/venomoth.png",
      Description: "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has."
    },
    {
      id: 50,
      name: "Diglett",
      types: ["Ground", ""],
      hp: 10,
      cp: 55,
      def: 25,
      Speed: 95,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/diglett.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/diglett.png",
      Description: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground."
    },
    {
      id: 51,
      name: "Dugtrio",
      types: ["Ground", ""],
      hp: 35,
      cp: 80,
      def: 50,
      Speed: 120,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dugtrio.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dugtrio.png",
      Description: "A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground."
    },
    {
      id: 52,
      name: "Meowth",
      types: ["Normal", ""],
      hp: 40,
      cp: 45,
      def: 35,
      Speed: 90,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/meowth.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/meowth.png",
      Description: "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change."
    },
    {
      id: 53,
      name: "Persian",
      types: ["Normal", ""],
      hp: 65,
      cp: 70,
      def: 60,
      Speed: 115,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/persian.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/persian.png",
      Description: "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness."
    },
    {
      id: 54,
      name: "Psyduck",
      types: ["Water", ""],
      hp: 50,
      cp: 52,
      def: 48,
      Speed: 55,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/psyduck.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/psyduck.png",
      Description: "While lulling its enemies with its vacant look, this wily Pokemon will use psychokinetic powers."
    },
    {
      id: 55,
      name: "Golduck",
      types: ["Water", ""],
      hp: 80,
      cp: 82,
      def: 78,
      Speed: 85,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/golduck.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/golduck.png",
      Description: "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa."
    },
    {
      id: 56,
      name: "Mankey",
      types: ["Fighting", ""],
      hp: 40,
      cp: 80,
      def: 35,
      Speed: 70,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/mankey.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/mankey.png",
      Description: "Extremely quick to anger. It could be docile one moment then thrashing away the next instant."
    },
    {
      id: 57,
      name: "Primeape",
      types: ["Fighting", ""],
      hp: 65,
      cp: 105,
      def: 60,
      Speed: 95,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/primeape.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/primeape.png",
      Description: "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught."
    },
    {
      id: 58,
      name: "Growlithe",
      types: ["Fire", ""],
      hp: 55,
      cp: 70,
      def: 45,
      Speed: 60,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/growlithe.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/growlithe.png",
      Description: "Very protective of its territory. It will bark and bite to repel intruders from its space."
    },
    {
      id: 59,
      name: "Arcanine",
      types: ["Fire", ""],
      hp: 90,
      cp: 110,
      def: 80,
      Speed: 95,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/arcanine.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/arcanine.png",
      Description: "A Pokemon that has been admired since the past for its beauty. It runs agilely as if on wings."
    },
    {
      id: 60,
      name: "Poliwag",
      types: ["Water", ""],
      hp: 40,
      cp: 50,
      def: 40,
      Speed: 90,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/poliwag.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/poliwag.png",
      Description: "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand."
    },
    {
      id: 61,
      name: "Poliwhirl",
      types: ["Water", ""],
      hp: 65,
      cp: 65,
      def: 65,
      Speed: 90,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/poliwhirl.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/poliwhirl.png",
      Description: "Capable of living in or out of water. When out of water, it sweats to keep its body slimy."
    },
    {
      id: 62,
      name: "Poliwrath",
      types: ["Water", "Fighting"],
      hp: 90,
      cp: 85,
      def: 95,
      Speed: 70,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/poliwrath.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/poliwrath.png",
      Description: "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers."
    },
    {
      id: 63,
      name: "Abra",
      types: ["Psychic", ""],
      hp: 25,
      cp: 20,
      def: 15,
      Speed: 90,
      Special: 105,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/abra.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/abra.png",
      Description: "Using its ability to read minds, it will identify impending danger and TELEPORT to safety."
    },
    {
      id: 64,
      name: "Kadabra",
      types: ["Psychic", ""],
      hp: 40,
      cp: 35,
      def: 30,
      Speed: 105,
      Special: 120,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kadabra.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kadabra.png",
      Description: "It emits special alpha waves from its body that induce headaches just by being close by."
    },
    {
      id: 65,
      name: "Alakazam",
      types: ["Psychic", ""],
      hp: 55,
      cp: 50,
      def: 45,
      Speed: 120,
      Special: 135,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/alakazam.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/alakazam.png",
      Description: "Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000."
    },
    {
      id: 66,
      name: "Machop",
      types: ["Fighting", ""],
      hp: 70,
      cp: 80,
      def: 50,
      Speed: 35,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/machop.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/machop.png",
      Description: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger."
    },
    {
      id: 67,
      name: "Machoke",
      types: ["Fighting", ""],
      hp: 80,
      cp: 100,
      def: 70,
      Speed: 45,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/machoke.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/machoke.png",
      Description: "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions."
    },
    {
      id: 68,
      name: "Machamp",
      types: ["Fighting", ""],
      hp: 90,
      cp: 130,
      def: 80,
      Speed: 55,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/machamp.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/machamp.png",
      Description: "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon."
    },
    {
      id: 69,
      name: "Bellsprout",
      types: ["Grass", "Poison"],
      hp: 50,
      cp: 75,
      def: 35,
      Speed: 40,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/bellsprout.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/bellsprout.png",
      Description: "A carnivorous Pokemon that traps and eats bugs. It uses its root feet to soak up needed moisture."
    },
    {
      id: 70,
      name: "Weepinbell",
      types: ["Grass", "Poison"],
      hp: 65,
      cp: 90,
      def: 50,
      Speed: 55,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/weepinbell.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/weepinbell.png",
      Description: "It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACid."
    },
    {
      id: 71,
      name: "Victreebel",
      types: ["Grass", "Poison"],
      hp: 80,
      cp: 105,
      def: 65,
      Speed: 70,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/victreebel.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/victreebel.png",
      Description: "Said to live in huge colonies deep in jungles, although no one has ever returned from there."
    },
    {
      id: 72,
      name: "Tentacool",
      types: ["Water", "Poison"],
      hp: 40,
      cp: 40,
      def: 35,
      Speed: 70,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/tentacool.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/tentacool.png",
      Description: "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid."
    },
    {
      id: 73,
      name: "Tentacruel",
      types: ["Water", "Poison"],
      hp: 80,
      cp: 70,
      def: 65,
      Speed: 100,
      Special: 120,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/tentacruel.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/tentacruel.png",
      Description: "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey."
    },
    {
      id: 74,
      name: "Geodude",
      types: ["Rock", "Ground"],
      hp: 40,
      cp: 80,
      def: 100,
      Speed: 20,
      Special: 30,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/geodude.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/geodude.png",
      Description: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them."
    },
    {
      id: 75,
      name: "Graveler",
      types: ["Rock", "Ground"],
      hp: 55,
      cp: 95,
      def: 115,
      Speed: 35,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/graveler.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/graveler.png",
      Description: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction."
    },
    {
      id: 76,
      name: "Golem",
      types: ["Rock", "Ground"],
      hp: 80,
      cp: 110,
      def: 130,
      Speed: 45,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/golem.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/golem.png",
      Description: "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage."
    },
    {
      id: 77,
      name: "Ponyta",
      types: ["Fire", ""],
      hp: 50,
      cp: 85,
      def: 55,
      Speed: 90,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ponyta.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ponyta.png",
      Description: "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time."
    },
    {
      id: 78,
      name: "Rapidash",
      types: ["Fire", ""],
      hp: 65,
      cp: 100,
      def: 70,
      Speed: 105,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/rapidash.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/rapidash.png",
      Description: "Very competitive, this Pokemon will chase anything that moves fast in the hopes of racing it."
    },
    {
      id: 79,
      name: "Slowpoke",
      types: ["Water", "Psychic"],
      hp: 90,
      cp: 65,
      def: 65,
      Speed: 15,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/slowpoke.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/slowpoke.png",
      Description: "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack."
    },
    {
      id: 80,
      name: "Slowbro",
      types: ["Water", "Psychic"],
      hp: 95,
      cp: 75,
      def: 110,
      Speed: 30,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/slowbro.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/slowbro.png",
      Description: "The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps."
    },
    {
      id: 81,
      name: "Magnemite",
      types: ["Electric", ""],
      hp: 25,
      cp: 35,
      def: 70,
      Speed: 45,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/magnemite.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/magnemite.png",
      Description: "Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves."
    },
    {
      id: 82,
      name: "Magneton",
      types: ["Electric", ""],
      hp: 50,
      cp: 60,
      def: 95,
      Speed: 70,
      Special: 120,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/magneton.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/magneton.png",
      Description: "Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up."
    },
    {
      id: 83,
      name: "Farfetch'd",
      types: ["Normal", "Flying"],
      hp: 52,
      cp: 65,
      def: 55,
      Speed: 60,
      Special: 58,
      GIF: "http://play.pokemonshowdown.com/sprites/bwani/farfetchd.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/farfetchd.png",
      Description: "The sprig of green onions it holds is its weapon. It is used much like a metal sword."
    },
    {
      id: 84,
      name: "Doduo",
      types: ["Normal", "Flying"],
      hp: 35,
      cp: 85,
      def: 45,
      Speed: 75,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/doduo.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/doduo.png",
      Description: "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints."
    },
    {
      id: 85,
      name: "Dodrio",
      types: ["Normal", "Flying"],
      hp: 60,
      cp: 110,
      def: 70,
      Speed: 100,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dodrio.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dodrio.png",
      Description: "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake."
    },
    {
      id: 86,
      name: "Seel",
      types: ["Water", ""],
      hp: 65,
      cp: 45,
      def: 55,
      Speed: 45,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/seel.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/seel.png",
      Description: "The protruding horn on its head is very hard. It is used for bashing through thick ice."
    },
    {
      id: 87,
      name: "Dewgong",
      types: ["Water", "Ice"],
      hp: 90,
      cp: 70,
      def: 80,
      Speed: 70,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dewgong.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dewgong.png",
      Description: "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters."
    },
    {
      id: 88,
      name: "Grimer",
      types: ["Poison", ""],
      hp: 80,
      cp: 80,
      def: 50,
      Speed: 25,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/grimer.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/grimer.png",
      Description: "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories."
    },
    {
      id: 89,
      name: "Muk",
      types: ["Poison", ""],
      hp: 105,
      cp: 105,
      def: 75,
      Speed: 50,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/muk.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/muk.png",
      Description: "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison."
    },
    {
      id: 90,
      name: "Shellder",
      types: ["Water", ""],
      hp: 30,
      cp: 65,
      def: 100,
      Speed: 40,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/shellder.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/shellder.png",
      Description: "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open."
    },
    {
      id: 91,
      name: "Cloyster",
      types: ["Water", "Ice"],
      hp: 50,
      cp: 95,
      def: 180,
      Speed: 70,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/cloyster.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/cloyster.png",
      Description: "When attacked, it launches its horns in quick volleys. Its innards have never been seen."
    },
    {
      id: 92,
      name: "Gastly",
      types: ["Ghost", "Poison"],
      hp: 30,
      cp: 35,
      def: 30,
      Speed: 80,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/gastly.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/gastly.png",
      Description: "Almost invisible, this gaseous Pokemon cloaks the target and puts it to sleep without notice."
    },
    {
      id: 93,
      name: "Haunter",
      types: ["Ghost", "Poison"],
      hp: 45,
      cp: 50,
      def: 45,
      Speed: 95,
      Special: 115,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/haunter.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/haunter.png",
      Description: "Because of its ability to slip through block walls, it is said to be from another dimension."
    },
    {
      id: 94,
      name: "Gengar",
      types: ["Ghost", "Poison"],
      hp: 60,
      cp: 65,
      def: 60,
      Speed: 110,
      Special: 130,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/gengar.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/gengar.png",
      Description: "Under a full moon, this Pokemon likes to mimic the shadows of people and laugh at their fright."
    },
    {
      id: 95,
      name: "Onix",
      types: ["Rock", "Ground"],
      hp: 35,
      cp: 45,
      def: 160,
      Speed: 70,
      Special: 30,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/onix.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/onix.png",
      Description: "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black."
    },
    {
      id: 96,
      name: "Drowzee",
      types: ["Psychic", ""],
      hp: 60,
      cp: 48,
      def: 45,
      Speed: 42,
      Special: 90,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/drowzee.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/drowzee.png",
      Description: "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams."
    },
    {
      id: 97,
      name: "Hypno",
      types: ["Psychic", ""],
      hp: 85,
      cp: 73,
      def: 70,
      Speed: 67,
      Special: 115,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/hypno.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/hypno.png",
      Description: "When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION."
    },
    {
      id: 98,
      name: "Krabby",
      types: ["Water", ""],
      hp: 30,
      cp: 105,
      def: 90,
      Speed: 50,
      Special: 25,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/krabby.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/krabby.png",
      Description: "Its pincers are not only powerful weapons, they are used for balance when walking sideways."
    },
    {
      id: 99,
      name: "Kingler",
      types: ["Water", ""],
      hp: 55,
      cp: 130,
      def: 115,
      Speed: 75,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kingler.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kingler.png",
      Description: "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use."
    },
    {
      id: 100,
      name: "Voltorb",
      types: ["Electric", ""],
      hp: 40,
      cp: 30,
      def: 50,
      Speed: 100,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/voltorb.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/voltorb.png",
      Description: "Usually found in power plants. Easily mistaken for a Pokeball, they have zapped many people."
    },
    {
      id: 101,
      name: "Electrode",
      types: ["Electric", ""],
      hp: 60,
      cp: 50,
      def: 70,
      Speed: 140,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/electrode.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/electrode.png",
      Description: "It stores electric energy under very high pressure. It often explodes with little or no provocation."
    },
    {
      id: 102,
      name: "Exeggcute",
      types: ["Grass", "Psychic"],
      hp: 60,
      cp: 40,
      def: 80,
      Speed: 40,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/exeggcute.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/exeggcute.png",
      Description: "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms."
    },
    {
      id: 103,
      name: "Exeggutor",
      types: ["Grass", "Psychic"],
      hp: 95,
      cp: 95,
      def: 85,
      Speed: 55,
      Special: 125,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/exeggutor.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/exeggutor.png",
      Description: "Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE."
    },
    {
      id: 104,
      name: "Cubone",
      types: ["Ground", ""],
      hp: 50,
      cp: 50,
      def: 95,
      Speed: 35,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/cubone.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/cubone.png",
      Description: "Because it never removes its skull helmet, no one has ever seen this Pokemon's real face."
    },
    {
      id: 105,
      name: "Marowak",
      types: ["Ground", ""],
      hp: 60,
      cp: 80,
      def: 110,
      Speed: 45,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/marowak.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/marowak.png",
      Description: "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets."
    },
    {
      id: 106,
      name: "Hitmonlee",
      types: ["Fighting", ""],
      hp: 50,
      cp: 120,
      def: 53,
      Speed: 87,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/hitmonlee.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/hitmonlee.png",
      Description: "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides."
    },
    {
      id: 107,
      name: "Hitmonchan",
      types: ["Fighting", ""],
      hp: 50,
      cp: 105,
      def: 79,
      Speed: 76,
      Special: 35,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/hitmonchan.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/hitmonchan.png",
      Description: "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see."
    },
    {
      id: 108,
      name: "Lickitung",
      types: ["Normal", ""],
      hp: 90,
      cp: 55,
      def: 75,
      Speed: 30,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/lickitung.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/lickitung.png",
      Description: "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies."
    },
    {
      id: 109,
      name: "Koffing",
      types: ["Poison", ""],
      hp: 40,
      cp: 65,
      def: 95,
      Speed: 35,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/koffing.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/koffing.png",
      Description: "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning."
    },
    {
      id: 110,
      name: "Weezing",
      types: ["Poison", ""],
      hp: 65,
      cp: 90,
      def: 120,
      Speed: 60,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/weezing.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/weezing.png",
      Description: "Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years."
    },
    {
      id: 111,
      name: "Rhyhorn",
      types: ["Ground", "Rock"],
      hp: 80,
      cp: 85,
      def: 95,
      Speed: 25,
      Special: 30,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/rhyhorn.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/rhyhorn.png",
      Description: "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying."
    },
    {
      id: 112,
      name: "Rhydon",
      types: ["Ground", "Rock"],
      hp: 105,
      cp: 130,
      def: 120,
      Speed: 40,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/rhydon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/rhydon.png",
      Description: "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees."
    },
    {
      id: 113,
      name: "Chansey",
      types: ["Normal", ""],
      hp: 250,
      cp: 5,
      def: 5,
      Speed: 50,
      Special: 105,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/chansey.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/chansey.png",
      Description: "A rare and elusive Pokemon that is said to bring happiness to those who manage to get it."
    },
    {
      id: 114,
      name: "Tangela",
      types: ["Grass", ""],
      hp: 65,
      cp: 55,
      def: 115,
      Speed: 60,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/tangela.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/tangela.png",
      Description: "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks."
    },
    {
      id: 115,
      name: "Kangaskhan",
      types: ["Normal", ""],
      hp: 105,
      cp: 95,
      def: 80,
      Speed: 90,
      Special: 40,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kangaskhan.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kangaskhan.png",
      Description: "The infant rarely ventures out of its mother's protective pouch until it is 3 years old."
    },
    {
      id: 116,
      name: "Horsea",
      types: ["Water", ""],
      hp: 30,
      cp: 40,
      def: 70,
      Speed: 60,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/horsea.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/horsea.png",
      Description: "Known to shoot down flying bugs with precision blasts of ink from the surface of the water."
    },
    {
      id: 117,
      name: "Seadra",
      types: ["Water", ""],
      hp: 55,
      cp: 65,
      def: 95,
      Speed: 85,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/seadra.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/seadra.png",
      Description: "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail."
    },
    {
      id: 118,
      name: "Goldeen",
      types: ["Water", ""],
      hp: 45,
      cp: 67,
      def: 60,
      Speed: 63,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/goldeen.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/goldeen.png",
      Description: "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen."
    },
    {
      id: 119,
      name: "Seaking",
      types: ["Water", ""],
      hp: 80,
      cp: 92,
      def: 65,
      Speed: 68,
      Special: 80,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/seaking.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/seaking.png",
      Description: "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks."
    },
    {
      id: 120,
      name: "Staryu",
      types: ["Water", ""],
      hp: 30,
      cp: 45,
      def: 55,
      Speed: 85,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/staryu.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/staryu.png",
      Description: "An enigmatic Pokemon that can effortlessly regenerate any appendage it loses in battle."
    },
    {
      id: 121,
      name: "Starmie",
      types: ["Water", "Psychic"],
      hp: 60,
      cp: 75,
      def: 85,
      Speed: 115,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/starmie.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/starmie.png",
      Description: "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem."
    },
    {
      id: 122,
      name: "Mr. Mime",
      types: ["Psychic", ""],
      hp: 40,
      cp: 45,
      def: 65,
      Speed: 90,
      Special: 100,
      GIF: "http://play.pokemonshowdown.com/sprites/bwani/mrmime.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/mrmime.png",
      Description: "If interrupted while it is miming, it will slap around the offender with its broad hands."
    },
    {
      id: 123,
      name: "Scyther",
      types: ["Bug", "Flying"],
      hp: 70,
      cp: 110,
      def: 80,
      Speed: 105,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/scyther.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/scyther.png",
      Description: "With ninja-like agility and speed, it can create the illusion that there is more than one."
    },
    {
      id: 124,
      name: "Jynx",
      types: ["Ice", "Psychic"],
      hp: 65,
      cp: 50,
      def: 35,
      Speed: 95,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/jynx.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/jynx.png",
      Description: "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it."
    },
    {
      id: 125,
      name: "Electabuzz",
      types: ["Electric", ""],
      hp: 65,
      cp: 83,
      def: 57,
      Speed: 105,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/electabuzz.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/electabuzz.png",
      Description: "Normally found near power plants, they can wander away and cause major blackouts in cities."
    },
    {
      id: 126,
      name: "Magmar",
      types: ["Fire", ""],
      hp: 65,
      cp: 95,
      def: 57,
      Speed: 93,
      Special: 85,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/magmar.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/magmar.png",
      Description: "Its body always burns with an orange glow that enables it to hide perfectly among flames."
    },
    {
      id: 127,
      name: "Pinsir",
      types: ["Bug", ""],
      hp: 65,
      cp: 125,
      def: 100,
      Speed: 85,
      Special: 55,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/pinsir.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/pinsir.png",
      Description: "If it fails to crush the victim in its pincers, it will swing it around and toss it hard."
    },
    {
      id: 128,
      name: "Tauros",
      types: ["Normal", ""],
      hp: 75,
      cp: 100,
      def: 95,
      Speed: 110,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/tauros.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/tauros.png",
      Description: "When it targets an enemy, it charges furiously while whipping its body with its long tails."
    },
    {
      id: 129,
      name: "Magikarp",
      types: ["Water", ""],
      hp: 20,
      cp: 10,
      def: 55,
      Speed: 80,
      Special: 20,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/magikarp.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/magikarp.png",
      Description: "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today."
    },
    {
      id: 130,
      name: "Gyarados",
      types: ["Water", "Flying"],
      hp: 95,
      cp: 125,
      def: 79,
      Speed: 81,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/gyarados.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/gyarados.png",
      Description: "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage."
    },
    {
      id: 131,
      name: "Lapras",
      types: ["Water", ""],
      hp: 130,
      cp: 85,
      def: 80,
      Speed: 60,
      Special: 95,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/lapras.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/lapras.png",
      Description: "A Pokemon that has been overhunted almost to extinction. It can ferry people across the water."
    },
    {
      id: 132,
      name: "Ditto",
      types: ["Normal", ""],
      hp: 48,
      cp: 48,
      def: 48,
      Speed: 48,
      Special: 48,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/ditto.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/ditto.png",
      Description: "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy."
    },
    {
      id: 133,
      name: "Eevee",
      types: ["Normal", ""],
      hp: 55,
      cp: 55,
      def: 50,
      Speed: 55,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/eevee.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/eevee.png",
      Description: "Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs."
    },
    {
      id: 134,
      name: "Vaporeon",
      types: ["Water", ""],
      hp: 130,
      cp: 65,
      def: 60,
      Speed: 65,
      Special: 110,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/vaporeon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/vaporeon.png",
      Description: "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's."
    },
    {
      id: 135,
      name: "Jolteon",
      types: ["Electric", ""],
      hp: 65,
      cp: 65,
      def: 60,
      Speed: 130,
      Special: 110,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/jolteon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/jolteon.png",
      Description: "It accumulates negative ions in the atmosphere to blast out 10000- volt lightning bolts."
    },
    {
      id: 136,
      name: "Flareon",
      types: ["Fire", ""],
      hp: 65,
      cp: 130,
      def: 60,
      Speed: 65,
      Special: 110,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/flareon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/flareon.png",
      Description: "When storing thermal energy in its body, its temperature could soar to over 1600 degrees."
    },
    {
      id: 137,
      name: "Porygon",
      types: ["Normal", ""],
      hp: 65,
      cp: 60,
      def: 70,
      Speed: 40,
      Special: 75,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/porygon.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/porygon.png",
      Description: "A Pokemon that consists entirely of programming code. Capable of moving freely in cyberspace."
    },
    {
      id: 138,
      name: "Omanyte",
      types: ["Rock", "Water"],
      hp: 35,
      cp: 40,
      def: 100,
      Speed: 35,
      Special: 90,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/omanyte.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/omanyte.png",
      Description: "Although long extinct, in rare cases, it can be genetically resurrected from fossils."
    },
    {
      id: 139,
      name: "Omastar",
      types: ["Rock", "Water"],
      hp: 70,
      cp: 60,
      def: 125,
      Speed: 55,
      Special: 115,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/omastar.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/omastar.png",
      Description: "A prehistoric Pokemon that died out when its heavy shell made it impossible to catch prey."
    },
    {
      id: 140,
      name: "Kabuto",
      types: ["Rock", "Water"],
      hp: 30,
      cp: 80,
      def: 90,
      Speed: 55,
      Special: 45,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kabuto.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kabuto.png",
      Description: "A Pokemon that was resurrected from a fossil found in what was once the ocean floor eons ago."
    },
    {
      id: 141,
      name: "Kabutops",
      types: ["Rock", "Water"],
      hp: 60,
      cp: 115,
      def: 105,
      Speed: 80,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/kabutops.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/kabutops.png",
      Description: "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids."
    },
    {
      id: 142,
      name: "Aerodactyl",
      types: ["Rock", "Flying"],
      hp: 80,
      cp: 105,
      def: 65,
      Speed: 130,
      Special: 60,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/aerodactyl.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/aerodactyl.png",
      Description: "A ferocious, prehistoric Pokemon that goes for the enemy's throat with its serrated saw-like fangs."
    },
    {
      id: 143,
      name: "Snorlax",
      types: ["Normal", ""],
      hp: 160,
      cp: 110,
      def: 65,
      Speed: 30,
      Special: 65,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/snorlax.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/snorlax.png",
      Description: "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful."
    },
    {
      id: 144,
      name: "Articuno",
      types: ["Ice", "Flying"],
      hp: 90,
      cp: 85,
      def: 100,
      Speed: 85,
      Special: 125,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/articuno.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/articuno.png",
      Description: "A legendary bird Pokemon that is said to appear to doomed people who are lost in icy mountains."
    },
    {
      id: 145,
      name: "Zapdos",
      types: ["Electric", "Flying"],
      hp: 90,
      cp: 90,
      def: 85,
      Speed: 100,
      Special: 125,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/zapdos.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/zapdos.png",
      Description: "A legendary bird Pokemon that is said to appear from clouds while dropping enormous lightning bolts."
    },
    {
      id: 146,
      name: "Moltres",
      types: ["Fire", "Flying"],
      hp: 90,
      cp: 100,
      def: 90,
      Speed: 90,
      Special: 125,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/moltres.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/moltres.png",
      Description: "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames."
    },
    {
      id: 147,
      name: "Dratini",
      types: ["Dragon", ""],
      hp: 41,
      cp: 64,
      def: 45,
      Speed: 50,
      Special: 50,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dratini.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dratini.png",
      Description: "Long considered a mythical Pokemon until recently when a small colony was found living underwater."
    },
    {
      id: 148,
      name: "Dragonair",
      types: ["Dragon", ""],
      hp: 61,
      cp: 84,
      def: 65,
      Speed: 70,
      Special: 70,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dragonair.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dragonair.png",
      Description: "A mystical Pokemon that exudes a gentle aura. Has the ability to change climate conditions."
    },
    {
      id: 149,
      name: "Dragonite",
      types: ["Dragon", "Flying"],
      hp: 91,
      cp: 134,
      def: 95,
      Speed: 80,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/dragonite.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/dragonite.png",
      Description: "An extremely rarely seen marine Pokemon. Its intelligence is said to match that of humans."
    },
    {
      id: 150,
      name: "Mewtwo",
      types: ["Psychic", ""],
      hp: 106,
      cp: 110,
      def: 90,
      Speed: 130,
      Special: 154,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/mewtwo.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/mewtwo.png",
      Description: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments."
    },
    {
      id: 151,
      name: "Mew",
      types: ["Psychic", ""],
      hp: 100,
      cp: 100,
      def: 100,
      Speed: 100,
      Special: 100,
      GIF: "https://play.pokemonshowdown.com/sprites/bwani/mew.gif",
      PNG: "https://play.pokemonshowdown.com/sprites/bw/mew.png",
      Description: "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide."
    }
];
